# Generated by Django 4.1.7 on 2023-02-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colleges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_id', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
    ]
