# Generated by Django 4.1.7 on 2023-02-26 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colleges',
            options={'verbose_name_plural': 'Colleges'},
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp_number', models.CharField(max_length=1000)),
                ('linkedin', models.URLField()),
                ('github', models.URLField()),
                ('question', models.TextField()),
                ('meal_type', models.CharField(max_length=1000)),
                ('tshirt_size', models.CharField(max_length=1000)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.colleges')),
            ],
        ),
    ]
