# Generated by Django 4.1.7 on 2023-02-26 03:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
